/**
 * Export Service for the ITU Reports Engine.
 * Supports CSV, XLSX (via SheetJS), and JSON export entirely client-side.
 * PDF is triggered via print stylesheet.
 */

import type { ReportColumn, ExportOptions, ReportRow } from './types'
import * as XLSX from 'xlsx'

// ─── Helpers ─────────────────────────────────────────────────────────────────

function getExportableColumns(columns: ReportColumn[], selectedKeys?: string[]): ReportColumn[] {
  const visible = columns.filter((c) => c.visible !== false)
  if (!selectedKeys || selectedKeys.length === 0) return visible
  return visible.filter((c) => selectedKeys.includes(c.key))
}

function getCellValue(col: ReportColumn, row: ReportRow): string | number {
  const raw = row[col.key]
  if (col.exportValue) return col.exportValue(raw, row)
  if (raw === null || raw === undefined) return ''
  if (typeof raw === 'number') return raw
  return String(raw)
}

function buildMatrix(
  rows: ReportRow[],
  columns: ReportColumn[],
): (string | number)[][] {
  const headers = columns.map((c) => c.header)
  const dataRows = rows.map((row) => columns.map((col) => getCellValue(col, row)))
  return [headers, ...dataRows]
}

function sanitizeFileName(name: string): string {
  return name.replace(/[^a-zA-Z0-9_\-. ]/g, '_').replace(/\s+/g, '_')
}

/** Helper to convert string/number value to raw number if possible */
function n(val: unknown): number {
  if (val === null || val === undefined) return 0
  if (typeof val === 'number') return val
  const parsed = parseFloat(String(val))
  return isNaN(parsed) ? 0 : parsed
}

function buildMetadataRows(options: ExportOptions): (string | number)[][] {
  const meta: (string | number)[][] = [
    ['ITU - International Mobile Top-Up Platform'],
    ['Report Name:', options.reportName ?? 'Report'],
    ['Generated By:', options.generatedBy ?? 'Admin User'],
    ['Generated Time:', new Date().toLocaleString()],
    ['Applied Filters:', options.filters.dateRange?.from ? `${options.filters.dateRange.from} to ${options.filters.dateRange.to}` : 'All Time'],
  ]
  
  if (options.summaryCards && options.summaryCards.length > 0) {
    meta.push([])
    meta.push(['SUMMARY STATS'])
    const headers = options.summaryCards.map(c => c.label)
    const values = options.summaryCards.map(c => {
      const val = n(c.value)
      if (c.currency) return `${c.currency} ${val.toFixed(2)}`
      if (c.suffix) return `${val}${c.suffix}`
      return val
    })
    meta.push(headers)
    meta.push(values)
  }
  
  meta.push([])
  meta.push(['REPORT DATA'])
  return meta
}

// ─── CSV ──────────────────────────────────────────────────────────────────────

export function exportToCSV(
  rows: ReportRow[],
  columns: ReportColumn[],
  options: ExportOptions,
): void {
  const cols   = getExportableColumns(columns, options.columns)
  const meta   = buildMetadataRows(options)
  const data   = buildMatrix(rows, cols)
  const matrix = [...meta, ...data]

  const csv = matrix
    .map((row) =>
      row
        .map((cell) => {
          const str = typeof cell === 'number' ? String(cell) : String(cell ?? '')
          return str.includes(',') || str.includes('"') || str.includes('\n')
            ? `"${str.replace(/"/g, '""')}"`
            : str
        })
        .join(','),
    )
    .join('\r\n')

  const blob     = new Blob(['\uFEFF' + csv], { type: 'text/csv;charset=utf-8;' })
  const url      = URL.createObjectURL(blob)
  const link     = document.createElement('a')
  const fileName = sanitizeFileName(options.fileName ?? 'report') + '.csv'

  link.setAttribute('href', url)
  link.setAttribute('download', fileName)
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}

// ─── XLSX ─────────────────────────────────────────────────────────────────────

export function exportToXLSX(
  rows: ReportRow[],
  columns: ReportColumn[],
  options: ExportOptions,
): void {
  const cols     = getExportableColumns(columns, options.columns)
  const meta     = buildMetadataRows(options)
  const data     = buildMatrix(rows, cols)
  const matrix   = [...meta, ...data]
  
  const ws       = XLSX.utils.aoa_to_sheet(matrix)
  const wb       = XLSX.utils.book_new()
  const sheetName = (options.reportName ?? 'Report').slice(0, 31)

  // Auto column widths
  ws['!cols'] = cols.map((col) => ({
    wch: Math.max(
      col.header.length,
      ...rows.slice(0, 100).map((row) => String(getCellValue(col, row)).length),
      10
    ) + 2,
  }))

  XLSX.utils.book_append_sheet(wb, ws, sheetName)
  XLSX.writeFile(wb, sanitizeFileName(options.fileName ?? 'report') + '.xlsx')
}

// ─── JSON ─────────────────────────────────────────────────────────────────────

export function exportToJSON(
  rows: ReportRow[],
  columns: ReportColumn[],
  options: ExportOptions,
): void {
  const cols = getExportableColumns(columns, options.columns)
  const data = rows.map((row) => {
    const obj: Record<string, string | number> = {}
    for (const col of cols) {
      obj[col.key] = getCellValue(col, row)
    }
    return obj
  })

  const json     = JSON.stringify(data, null, 2)
  const blob     = new Blob([json], { type: 'application/json' })
  const url      = URL.createObjectURL(blob)
  const link     = document.createElement('a')
  const fileName = sanitizeFileName(options.fileName ?? 'report') + '.json'

  link.setAttribute('href', url)
  link.setAttribute('download', fileName)
  document.body.appendChild(link)
  link.click()
  document.body.removeChild(link)
  URL.revokeObjectURL(url)
}

// ─── PDF (print) ──────────────────────────────────────────────────────────────

export function exportToPDF(): void {
  // Add temporary print style tag to make the layout print-perfect
  const style = document.createElement('style')
  style.id = 'print-perf-styles'
  style.innerHTML = `
    @media print {
      /* Hide all sidebars, navigation, select lists, pagination and interactive inputs */
      nav, aside, footer, button, .no-print, .print\\:hidden, [role="tablist"], [data-slot="pagination"], [data-slot="select-trigger"], [data-slot="input"], .hidden-print {
        display: none !important;
      }
      
      /* Make background white and text dark for high contrast print */
      body, html {
        background: white !important;
        color: black !important;
      }
      
      /* Ensure charts are fully visible and don't get clipped */
      .recharts-responsive-container {
        width: 100% !important;
        height: auto !important;
      }
      
      /* Prevent table rows and cards from breaking awkwardly across pages */
      tr, card, .card {
        page-break-inside: avoid !important;
      }
      
      /* Reset page counter for professional document footer formatting */
      @page {
        margin: 1.5cm;
        size: auto;
      }
    }
  `
  document.head.appendChild(style)
  
  // Trigger browser print dialog
  window.print()
  
  // Clean up styles after print
  setTimeout(() => {
    const el = document.getElementById('print-perf-styles')
    if (el) el.remove()
  }, 1000)
}

// ─── Dispatcher ──────────────────────────────────────────────────────────────

export function runExport(
  rows: ReportRow[],
  columns: ReportColumn[],
  options: ExportOptions,
): void {
  switch (options.format) {
    case 'csv':  return exportToCSV(rows, columns, options)
    case 'xlsx': return exportToXLSX(rows, columns, options)
    case 'json': return exportToJSON(rows, columns, options)
    case 'pdf':  return exportToPDF()
  }
}
